import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync } from 'node:crypto';
import { buildIntent, buildReceipt, signReceipt, verifyReceipt, canonicalize, hashJson } from '../../src/index.mjs';
const keys = generateKeyPairSync('ed25519'); const priv = keys.privateKey.export({ type: 'pkcs8', format: 'pem' }); const pub = keys.publicKey.export({ type: 'spki', format: 'pem' });
const sender = `0x${'a'.repeat(40)}`; const recipient = `0x${'b'.repeat(40)}`;
const intent = buildIntent({ intentId: 'i-1', chainId: 8453, action: 'TRANSFER', asset: 'eip155:8453/native', amount: '10', sender, recipient, validUntil: 2000000000, nonce: '1' });
const execution = { chainId: 8453, txHash: '0x' + '1'.repeat(64), status: 'CONFIRMED', observedAt: 100, sender, recipient, asset: 'eip155:8453/native', amount: '10', finalityState: 'CONFIRMED' };
test('canonical JSON sorts objects but preserves arrays', () => { assert.equal(hashJson({ b: 2, a: 1 }), hashJson({ a: 1, b: 2 })); assert.notEqual(hashJson({ a: [1, 2] }), hashJson({ a: [2, 1] })); assert.equal(canonicalize({ a: null, b: 'x', c: 2 }), '{"a":null,"b":"x","c":2}'); });
test('receipt verifies offline and detects mutation', () => { const receipt = signReceipt(buildReceipt({ intent, execution, issuer: 'test', keyId: 'k1', issuedAt: 100 }), priv); assert.equal(verifyReceipt(receipt, pub, { keyId: 'k1', now: 101 }).valid, true); assert.equal(verifyReceipt({ ...receipt, outcome: 'FAILED' }, pub, { keyId: 'k1', now: 101 }).code, 'INVALID_SIGNATURE'); assert.equal(verifyReceipt({ ...receipt, executionHash: 'bad' }, pub, { keyId: 'k1', now: 101 }).code, 'EXECUTION_HASH_MISMATCH'); });
test('intent fields bind to completed execution', () => { assert.equal(buildReceipt({ intent, execution, issuer: 'test' }).outcome, 'COMPLETED'); assert.equal(buildReceipt({ intent, execution: { ...execution, recipient: `0x${'c'.repeat(40)}` }, issuer: 'test' }).outcome, 'UNDETERMINED'); assert.equal(buildReceipt({ intent, execution: { ...execution, status: 'PENDING' }, issuer: 'test' }).outcome, 'PENDING'); });
