export const chains: Record<number, string> = { 1: 'Ethereum', 8453: 'Base', 42161: 'Arbitrum' }
export const short = (value?: string | null, left = 10, right = 7) => !value ? '—' : value.length <= left + right + 1 ? value : `${value.slice(0, left)}…${value.slice(-right)}`
const dateTimeFormatter = new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' })
export const dateTime = (seconds?: number | null) => seconds ? dateTimeFormatter.format(seconds * 1000) : '—'
export const relative = (seconds?: number) => seconds ? new Intl.RelativeTimeFormat(undefined, { numeric: 'auto' }).format(Math.round((seconds - Date.now() / 1000) / 86400), 'day') : '—'
export const toUnix = (date: string) => Math.floor(new Date(date).getTime() / 1000)
export const fromUnix = (seconds: number) => new Date(seconds * 1000).toISOString().slice(0, 16)
export const reasonText: Record<string, string> = {
  CHAIN_MISMATCH: 'The execution was observed on a different chain.', ACTION_MISMATCH: 'The observed transaction action differs from the authorized action.', SENDER_MISMATCH: 'The observed sender differs from the authorized sender.', RECIPIENT_MISMATCH: 'The observed recipient differs from the authorized recipient.', CALL_TARGET_MISMATCH: 'The transaction target differs from the signed exact-call constraint.', CALLDATA_MISMATCH: 'The transaction calldata hash differs from the signed exact-call constraint.', TRANSACTION_VALUE_MISMATCH: 'The native transaction value differs from the signed exact-call constraint.', ASSET_MISMATCH: 'The observed asset differs from the authorized asset.', AMOUNT_MISMATCH: 'The observed amount differs from the authorized amount.', NONCE_MISMATCH: 'The transaction nonce differs from the authorized nonce.', OUTSIDE_TIME_WINDOW: 'The block timestamp falls outside the intent validity window.', OUTSIDE_AUTHORIZATION_WINDOW: 'The block timestamp falls outside the signed authorization validity window.', AUTHORIZATION_AFTER_EXECUTION: 'PriorSeal accepted the authorization after the observed block execution time.', INSUFFICIENT_FINALITY: 'The requested confirmation threshold was not reached.', GAS_LIMIT_EXCEEDED: 'Observed gas use exceeds the intent constraint.', AMBIGUOUS_TRANSFER: 'More than one transfer could match the intent.', EXECUTION_UNAVAILABLE: 'Execution data is not available from the observation source.', EXECUTION_PENDING: 'The transaction has not reached a final state.', EXECUTION_NOT_FOUND: 'The transaction was not found by the observation source.', EXECUTION_REORGED: 'The previously observed execution is no longer canonical.', EXECUTOR_MISMATCH: 'The transaction sender is not the agent executor named in the signed authorization.'
}
export const verificationText: Record<string, string> = {
  OK: 'The receipt evidence, execution state and compliance assessment passed local verification.', UNKNOWN_KEY: 'The receipt key is not present in the available key registry.', MISSING_SIGNATURE: 'The receipt does not contain a signature.', UNSUPPORTED_SCHEMA: 'This receipt schema is not supported by this verifier.', UNSUPPORTED_ALGORITHM: 'This signature algorithm is not supported.', INVALID_DOMAIN: 'The receipt domain does not match the PriorSeal receipt domain.', EXECUTION_HASH_MISMATCH: 'The embedded execution does not match its recorded execution hash.', EXECUTION_STATUS_MISMATCH: 'The signed execution status differs from the embedded observation.', COMPLIANCE_MISMATCH: 'The signed compliance assessment differs from the result recomputed locally.', INVALID_SIGNATURE: 'The signature could not be verified with the selected public key.', INVALID_KEY: 'The selected key cannot verify this issuer or has been revoked.', KEY_NOT_YET_VALID: 'The receipt predates this key validity window.', KEY_EXPIRED: 'The receipt was issued after this key validity window.', NOT_YET_VALID: 'The receipt was issued in the future relative to the verifier clock.', INVALID_RECEIPT: 'The receipt is malformed.', UNSUPPORTED_CRYPTO: 'This browser does not support the cryptography required for local verification.', INVALID_TIMESTAMP_EVIDENCE: 'The RFC 3161 timestamp evidence is missing or malformed.', INVALID_TIMESTAMP_SIGNATURE: 'The DigiCert timestamp signature or certificate path is invalid.', TIMESTAMP_AFTER_EXECUTION: 'The trusted timestamp was issued after the observed execution.', TIMESTAMP_CLOCK_SKEW: 'The timestamp is outside the clock-skew window approved in the authorization policy.', TIMESTAMP_POLICY_MISMATCH: 'Timestamp evidence is present but was not required by the signed policy.', INVALID_AUTHORIZATION_SIGNATURE: 'The user or organization signature over the intent is invalid.', AUTHORIZATION_AFTER_EXECUTION: 'The authorization was accepted after the observed execution.', INVALID_AUTHORIZATION_RECEIPT: 'The issuer acceptance statement is invalid.', BINDING_MISMATCH: 'The signed binding result differs from the result recomputed locally.', OUTCOME_MISMATCH: 'The signed outcome differs from the outcome recomputed locally.', AUTHORIZATION_REQUIRES_CHAIN_VERIFICATION: 'This Safe/ERC-1271 authorization requires contract-state verification through an EVM source; the default server checks current state.'
}
