import test from 'node:test';
// TypeScript source; the matching .mjs file is generated by npm run core:build.
import assert from 'node:assert/strict';
import { assertCloudflareBindings, cloudflareRuntimeEnvironment, createCloudflareRateLimiter } from '../../src/bootstrap/cloudflare-bindings.mjs';

type CloudflareBindings = Parameters<typeof assertCloudflareBindings>[0];

function bindings(overrides: Record<string, unknown> = {}): CloudflareBindings {
  return {
    DB: { prepare() {} },
    OBSERVATION_QUEUE: { async send() {} },
    HTTP_RATE_LIMITER: { async limit() { return { success: true }; } },
    CF_VERSION_METADATA: { id: 'version-id', tag: '0123456789abcdef0123456789abcdef01234567' },
    ...overrides,
  } as unknown as CloudflareBindings;
}

test('Cloudflare runtime requires production bindings and uses the Git version tag', () => {
  const environment = bindings();
  assert.doesNotThrow(() => assertCloudflareBindings(environment));
  assert.equal(cloudflareRuntimeEnvironment(environment).PRIORSEAL_BUILD_VERSION, environment.CF_VERSION_METADATA.tag);
  assert.equal(cloudflareRuntimeEnvironment(environment).PRIORSEAL_DATABASE_BACKEND, 'd1');
  assert.equal(cloudflareRuntimeEnvironment(bindings({ CF_VERSION_METADATA: { id: 'version-only' } })).PRIORSEAL_BUILD_VERSION, 'version-only');
  assert.throws(() => assertCloudflareBindings(bindings({ HTTP_RATE_LIMITER: undefined })), /HTTP_RATE_LIMITER/);
  assert.throws(() => assertCloudflareBindings(bindings({ DB: undefined })), /DB D1 binding/);
  assert.throws(() => assertCloudflareBindings(bindings({ CF_VERSION_METADATA: undefined })), /CF_VERSION_METADATA/);
});

test('Cloudflare rate limiter awaits the shared binding and fails closed', async () => {
  const keys: string[] = [];
  const limiter = createCloudflareRateLimiter({ async limit(input) { keys.push(input.key); return { success: keys.length === 1 }; } });
  assert.equal(await limiter.allow('principal-1'), true);
  assert.equal(await limiter.allow('principal-1'), false);
  assert.deepEqual(keys, ['principal-1', 'principal-1']);
  await assert.rejects(() => createCloudflareRateLimiter({ async limit() { throw new Error('binding failed'); } }).allow('principal-1'), (error: any) => error.code === 'RATE_LIMITER_UNAVAILABLE');
});
