import assert from 'node:assert/strict';
// TypeScript source; the matching .mjs file is generated by npm run core:build.
import { readFileSync } from 'node:fs';
import test from 'node:test';
import {
  runFixtureChecks,
  verifyThreeObjectFlow,
} from '../../examples/insight-boundaryattest-three-object-v0.2/verify.mjs';

const fixtureUrl = new URL(
  '../../examples/insight-boundaryattest-three-object-v0.2/',
  import.meta.url,
);
const readJson = (name: string): any =>
  JSON.parse(readFileSync(new URL(name, fixtureUrl), 'utf8'));

test('three-object fixture passes the matching flow and all documented fail-closed vectors', async () => {
  const results = await runFixtureChecks({ log: () => {} });
  assert.deepEqual(
    results.map((result) => result.code),
    [
      'OK',
      'INSIGHT_SOURCE_UID_MISMATCH',
      'INSIGHT_SOURCE_SIGNER_UNTRUSTED',
      'INSIGHT_SOURCE_EVIDENCE_EXPIRED',
      'INSIGHT_CONTEXT_COMMITMENT_DIGEST_MISMATCH',
      'BOUNDARYATTEST_SIGNATURE_INVALID',
      'BOUNDARYATTEST_KEY_ID_MISMATCH',
      'BOUNDARYATTEST_GOVERNANCE_VERDICT_INVALID',
      'BOUNDARYATTEST_GOVERNANCE_STOPPED',
      'BOUNDARYATTEST_CORE_EVENT_SEMANTICS_INVALID',
      'BOUNDARYATTEST_EXPORT_STALE',
      'BOUNDARYATTEST_DECISION_STALE',
      'BOUNDARYATTEST_EXPORT_REPLAYED',
      'BOUNDARYATTEST_DECISION_REPLAYED',
      'BOUNDARYATTEST_SUBJECT_ACTION_REF_MISMATCH',
      'BOUNDARYATTEST_SCOPE_CALLDATA_MISMATCH',
      'BOUNDARYATTEST_SCOPE_TARGET_MISMATCH',
      'BOUNDARYATTEST_INSIGHT_REFERENCE_MISMATCH',
      'BOUNDARYATTEST_CONTEXT_COMMITMENT_DIGEST_MISMATCH',
      'BOUNDARYATTEST_CONTEXT_COMMITMENT_MISSING',
      'BOUNDARYATTEST_SIGNER_CONTEXT_COMMITMENT_DIGEST_MISMATCH',
      'PRIORSEAL_RECEIPT_NOT_COMPLIANT',
      'PRIORSEAL_VALIDITY_EXCEEDS_EVIDENCE',
    ],
  );
  assert.equal(
    results[0].valueConclusion,
    'BOUNDARYATTEST_ADDS_GOVERNANCE_HANDOFF',
  );
  assert.equal(results[0].deletionTest.result, 'MATERIAL_FACT_LOST');
  assert.match(
    results[0].deletionTest.unverifiableFact!,
    /governance signer reviewed/,
  );
});

test('PriorSeal separately binds Insight, the BoundaryAttest claim, and its expected signer', () => {
  const expected = readJson('expected.json');
  const receipt = readJson('priorseal-receipt-matching.json');
  const commitments =
    receipt.authorizationEvidence.authorization.intent.contextCommitments;
  assert.deepEqual(
    commitments.map((entry: any) => entry.namespace),
    [
      'boundaryattest.governance-signer.spki-sha256.v1',
      'boundaryattest.insight-handoff.jcs-claim.v0.2',
      'insight.pretrade-pair.v1',
    ],
  );
  assert.equal(
    commitments.find(
      (entry: any) => entry.namespace === expected.boundaryAttest.signerNamespace,
    ).digest,
    `0x${expected.boundaryAttest.publicKeyId.slice('sha256:'.length)}`,
  );
  assert.equal(
    commitments.find((entry: any) => entry.namespace === expected.insight.namespace)
      .digest,
    expected.insight.digest,
  );
});

test('deletion test returns reference-only when no material fact is lost', async () => {
  const expected = readJson('expected.json');
  expected.boundaryAttest.deletionTest.materialFactLost = false;
  expected.boundaryAttest.deletionTest.providerReason =
    'Reject the portable claim because the native evidence already preserves the relevant fact.';
  const result = await verifyThreeObjectFlow({
    insightSource: readJson('insight-source.json'),
    insightDestination: readJson('insight-destination.json'),
    boundaryReceipt: readJson('boundaryattest-receipt.json'),
    boundaryPublicKey: readFileSync(
      new URL('boundaryattest-public-key.pem', fixtureUrl),
      'utf8',
    ),
    priorSealReceipt: readJson('priorseal-receipt-matching.json'),
    trustedIssuerKeys: readJson('priorseal-trusted-issuer-keys.json'),
    expected,
  });
  assert.equal(result.code, 'OK');
  assert.equal(result.valueConclusion, 'BOUNDARYATTEST_REFERENCE_ONLY');
  assert.equal(result.deletionTest.result, 'NO_MATERIAL_FACT_LOST');
  assert.equal(result.deletionTest.unverifiableFact, null);
});

test('replay state mutates only after every verification layer succeeds', async () => {
  const expected = readJson('expected.json');
  const trustedIssuerKeys = readJson('priorseal-trusted-issuer-keys.json');
  const boundaryPublicKey = readFileSync(
    new URL('boundaryattest-public-key.pem', fixtureUrl),
    'utf8',
  );
  const common = {
    insightSource: readJson('insight-source.json'),
    insightDestination: readJson('insight-destination.json'),
    boundaryReceipt: readJson('boundaryattest-receipt.json'),
    boundaryPublicKey,
    trustedIssuerKeys,
    expected,
  };
  const usedSignedExports = new Set();
  const usedDecisionIds = new Set();
  const failed = await verifyThreeObjectFlow({
    ...common,
    priorSealReceipt: readJson(
      'priorseal-receipt-wrong-insight-commitment.json',
    ),
    usedSignedExports,
    usedDecisionIds,
  });
  assert.equal(failed.code, 'INSIGHT_CONTEXT_COMMITMENT_DIGEST_MISMATCH');
  assert.equal(usedSignedExports.size, 0);
  assert.equal(usedDecisionIds.size, 0);

  const passing = await verifyThreeObjectFlow({
    ...common,
    priorSealReceipt: readJson('priorseal-receipt-matching.json'),
    usedSignedExports,
    usedDecisionIds,
  });
  assert.equal(passing.code, 'OK');
  assert.equal(usedSignedExports.size, 1);
  assert.equal(usedDecisionIds.size, 1);
});
