import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, sign } from 'node:crypto';
import { privateKeyToAccount } from 'viem/accounts';
import { authorizeIntent, authorizationTypedData, buildAuthorization, buildAuthorizedReceipt, canonicalize, createMemoryStore, hashJson } from '../../src/index.mjs';
import { signReceipt } from '../../src/domain/receipt.mjs';
import { verifyReceiptLocally } from '../../sdk/dist/verifier.js';

test('SDK verifier accepts signed v2 Merkle receipts but rejects tampered proofs', async () => {
  const keys = generateKeyPairSync('ed25519');
  const privateKey = keys.privateKey.export({ type: 'pkcs8', format: 'pem' });
  const publicKey = keys.publicKey.export({ type: 'spki', format: 'pem' });
  const signer = privateKeyToAccount(`0x${'1'.repeat(64)}`);
  const executor = `0x${'a'.repeat(40)}`;
  const intent = { intentId: 'sdk-merkle-hotfix', chainId: 8453, action: 'TRANSFER', asset: 'eip155:8453/native', amount: '10', sender: executor, recipient: `0x${'b'.repeat(40)}`, validUntil: 2_000, nonce: '7' };
  const policy = { policyId: 'separated-authority-v1', requireDistinctAuthorizerAndExecutor: true };
  const draft = buildAuthorization({ intent, principal: { type: 'user', id: 'user-1', account: signer.address }, authorizer: { type: 'eip712', address: signer.address }, delegate: { agentId: 'agent-1', executor }, issuedAt: 1_000, notBefore: 1_000, expiresAt: 2_000, authorizationNonce: `0x${'2'.repeat(64)}`, maxUses: '1', audience: 'priorseal', policyHash: `0x${hashJson(policy)}` });
  const authorization = buildAuthorization({ ...draft, signature: await signer.signTypedData(authorizationTypedData(draft)) });
  const store = createMemoryStore({ clock: () => 1_001_000 });
  const accepted = await authorizeIntent({ input: authorization, store, privateKeyPem: privateKey, issuer: 'test', keyId: 'key-1', policy, now: () => 1_001_000 });
  await store.appendAuthorizationLog({ authorizationHash: 'f'.repeat(64), acceptedAt: 1_002 });
  const entries = await store.listAuthorizationLog();
  assert.equal(entries.length, 2);
  const leaf = (entryHash) => hashJson({ domain: 'priorseal/transparency-leaf/v1', entryHash });
  const merkleRoot = hashJson({ domain: 'priorseal/transparency-node/v1', left: leaf(entries[0].entryHash), right: leaf(entries[1].entryHash) });
  const checkpoint = { schema: 'priorseal.transparency-checkpoint.v2', domain: 'priorseal/transparency-checkpoint/v2', size: 2, headEntryHash: entries[1].entryHash, merkleRoot, issuedAt: 1_099, issuer: 'test', algorithm: 'Ed25519', keyId: 'key-1', anchor: null };
  const signature = sign(null, Buffer.from(canonicalize(checkpoint)), privateKey).toString('base64url');
  const transparency = { checkpoint: { ...checkpoint, signature }, proof: [{ side: 'right', hash: leaf(entries[1].entryHash) }] };
  const execution = { chainId: 8453, txHash: `0x${'3'.repeat(64)}`, status: 'CONFIRMED', action: 'TRANSFER', sender: executor, recipient: intent.recipient, asset: intent.asset, amount: intent.amount, nonce: intent.nonce, executedAt: 1_100, observedAt: 1_101, confirmations: 12, gasUsed: '21000', transfers: [], finalityState: 'CONFIRMED' };
  const receipt = signReceipt(buildAuthorizedReceipt({ authorization: accepted.response.authorization, acceptance: accepted.response.acceptance, policyEvidence: accepted.response.policyEvidence, transparency, execution, issuer: 'test', keyId: 'key-1', issuedAt: 1_101 }), privateKey);
  const trust = { issuer: 'test', keyId: 'key-1', algorithm: 'Ed25519', publicKey, status: 'active', validFrom: null, validUntil: null };
  assert.equal((await verifyReceiptLocally(receipt, { trustedKeys: trust, now: 1_200 })).valid, true);
  const tampered = structuredClone(receipt);
  tampered.authorizationEvidence.transparency.proof[0].hash = 'e'.repeat(64);
  assert.equal((await verifyReceiptLocally(signReceipt(tampered, privateKey), { trustedKeys: trust, now: 1_200 })).code, 'INVALID_TRANSPARENCY_PROOF');
  const anchor = { type: 'eip155', chainId: 8453, contract: `0x${'c'.repeat(40)}`, txHash: `0x${'d'.repeat(64)}`, blockNumber: 10, anchoredAt: 1_099, size: 2, headEntryHash: entries[1].entryHash, merkleRoot };
  const anchoredCheckpoint = { ...checkpoint, anchor };
  const anchoredTransparency = { checkpoint: { ...anchoredCheckpoint, signature: sign(null, Buffer.from(canonicalize(anchoredCheckpoint)), privateKey).toString('base64url') }, proof: transparency.proof };
  const anchoredReceipt = signReceipt(buildAuthorizedReceipt({ authorization: accepted.response.authorization, acceptance: accepted.response.acceptance, policyEvidence: accepted.response.policyEvidence, transparency: anchoredTransparency, execution, issuer: 'test', keyId: 'key-1', issuedAt: 1_101 }), privateKey);
  assert.equal((await verifyReceiptLocally(anchoredReceipt, { trustedKeys: trust, now: 1_200 })).valid, true);
  const invalidAnchor = { ...anchor, merkleRoot: 'e'.repeat(64) };
  const invalidCheckpoint = { ...checkpoint, anchor: invalidAnchor };
  const invalidTransparency = { checkpoint: { ...invalidCheckpoint, signature: sign(null, Buffer.from(canonicalize(invalidCheckpoint)), privateKey).toString('base64url') }, proof: transparency.proof };
  const invalidReceipt = signReceipt(buildAuthorizedReceipt({ authorization: accepted.response.authorization, acceptance: accepted.response.acceptance, policyEvidence: accepted.response.policyEvidence, transparency: invalidTransparency, execution, issuer: 'test', keyId: 'key-1', issuedAt: 1_101 }), privateKey);
  assert.equal((await verifyReceiptLocally(invalidReceipt, { trustedKeys: trust, now: 1_200 })).code, 'INVALID_TRANSPARENCY_PROOF');
});
