// Local simulation; no RPC, production key, deployment, or transaction broadcast.
import assert from 'node:assert/strict';
import { generateKeyPairSync } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import { privateKeyToAccount } from 'viem/accounts';
import * as prior from '../../sdk/dist/index.js';
import { authorizeIntent, authorizationTypedData, buildAuthorization, buildAuthorizedReceipt, createMemoryStore, signReceipt, verifyAuthorization } from '../../src/index.mjs';
import { rwaFixture, signRwaFixture } from './fixture.mjs';

const insightRoot=resolve(process.argv[2] ?? new URL('../../../insight/',import.meta.url).pathname);
const imported=await import(pathToFileURL(resolve(insightRoot,'sdk/dist/index.js')));
const insight=imported.default ?? imported;
assert.equal(readFileSync(resolve(insightRoot,'sdk/src/rwa.ts'),'utf8'),readFileSync(new URL('../../sdk/src/insight-rwa.ts',import.meta.url),'utf8'),'Vendored protocol must match Insight exactly');
const assessmentKey=privateKeyToAccount('0x'+'12'.repeat(32)), principal=privateKeyToAccount('0x'+'34'.repeat(32));
const f=rwaFixture(insight), authority=await signRwaFixture(insight,assessmentKey,f);
assert.equal(prior.rwaReportDigest(authority.proof.report),authority.proof.digest);
assert.equal((await prior.verifyRwaReport(authority.proof,authority.trust,f.now)).valid,true);
const intent=await prior.buildRwaBoundIntent({transaction:f.transaction,intentId:'simulation-rwa-exact-call',asset:'eip155:8453/erc20:'+f.input.instrument.tokenAddress,amount:f.input.request.amount,validUntil:f.now+100},authority,f.now);
const draft=buildAuthorization({intent,principal:{type:'user',id:'simulation-user',account:principal.address},authorizer:{type:'eip712',address:principal.address},delegate:{agentId:'simulation-rwa-agent',executor:f.transaction.from},issuedAt:f.now,notBefore:f.now,expiresAt:intent.validUntil,authorizationNonce:'0x'+'55'.repeat(32),maxUses:'1',audience:'priorseal',policyHash:'0x'+'00'.repeat(32)});
const authorization=buildAuthorization({...draft,signature:await principal.signTypedData(authorizationTypedData(draft))});
const issuerKeys=generateKeyPairSync('ed25519'),privateKeyPem=issuerKeys.privateKey.export({type:'pkcs8',format:'pem'}),publicKeyPem=issuerKeys.publicKey.export({type:'spki',format:'pem'});
const store=createMemoryStore({clock:()=>f.now*1000});
const accepted=await authorizeIntent({input:authorization,store,privateKeyPem,issuer:'simulation-rwa-attester',keyId:'simulation-1',now:()=>f.now*1000});
const later=rwaFixture(insight,f.now+2),execution=await signRwaFixture(insight,assessmentKey,later);
execution.trust=structuredClone(authority.trust);
const pair={intent,authority,execution,authorityTime:f.now};
let callbacks=0;
await prior.withRwaExecutionPair(pair,f.transaction,async transaction=>{
  assert.equal((await verifyAuthorization(accepted.response.authorization,{now:f.now+2})).valid,true);
  assert.deepEqual(transaction,f.transaction);
  // Production integration must reserve its signer/nonce atomically before broadcast.
  assert.equal((await store.bindAuthorization(authorization.authorizationId,'0x'+'66'.repeat(32))).ok,true);
  callbacks++;
},()=>f.now+2);
assert.equal(callbacks,1);
assert.equal((await store.bindAuthorization(authorization.authorizationId,'0x'+'77'.repeat(32))).code,'AUTHORIZATION_ALREADY_USED');
const observed={chainId:8453,txHash:'0x'+'66'.repeat(32),status:'CONFIRMED',action:'CONTRACT_CALL',sender:f.transaction.from,recipient:f.transaction.to,target:f.transaction.to,calldataHash:f.input.request.call.calldataHash,nativeValue:'0',asset:intent.asset,amount:intent.amount,nonce:intent.nonce,executedAt:f.now+2,observedAt:f.now+3,confirmations:12,gasUsed:'100000',transfers:[],finalityState:'CONFIRMED'};
const receipt=signReceipt(buildAuthorizedReceipt({authorization:accepted.response.authorization,acceptance:accepted.response.acceptance,policyEvidence:accepted.response.policyEvidence,execution:observed,issuer:'simulation-rwa-attester',keyId:'simulation-1',issuedAt:f.now+3}),privateKeyPem);
const bundle={receipt,authority:authority.proof,execution:execution.proof};
const options={now:f.now+3,trustedKeys:{issuer:'simulation-rwa-attester',keyId:'simulation-1',algorithm:'Ed25519',publicKey:publicKeyPem,status:'active',validFrom:f.now-60,validUntil:f.now+60}};
const verified=await prior.verifyRwaReceiptBundle(bundle,authority.trust,options);
assert.equal(verified.valid,true,JSON.stringify(verified));
const tampered=structuredClone(bundle);tampered.receipt.execution.calldataHash='0x'+'00'.repeat(32);
assert.equal((await prior.verifyRwaReceiptBundle(tampered,authority.trust,options)).valid,false);
const changed=rwaFixture(insight,f.now+2);changed.input.market.halt='HALTED';
const halted=await signRwaFixture(insight,assessmentKey,changed);halted.trust=structuredClone(authority.trust);
await assert.rejects(prior.withRwaExecutionPair({...pair,execution:halted},f.transaction,async()=>callbacks++,()=>f.now+2));
assert.equal(callbacks,1);
const haltedBundle={...bundle,execution:halted.proof};
assert.equal((await prior.verifyRwaReceiptBundle(haltedBundle,authority.trust,options)).valid,false);
assert.equal((await prior.verifyRwaReceiptBundle(bundle,{...authority.trust,environment:'production'},options)).valid,false);
assert.equal((await prior.verifyRwaReceiptBundle(bundle,authority.trust,{now:f.now+3})).valid,false);
console.log(JSON.stringify({environment:'SIMULATION',networkCalls:0,sourceParity:true,crossSdkSignature:true,principalAuthorized:true,exactCallCallbacks:callbacks,receiptVerified:verified.valid,replayRejected:true,haltBeforeExecutionRejected:true,receiptTamperRejected:true,productionTrustRejectsSimulation:true,missingIssuerKeyRejected:true,productionReadiness:'NOT_ACTIVATED'},null,2));
