import test, { type TestContext } from 'node:test';
// TypeScript source; the matching .mjs file is generated by npm run core:build.
import assert from 'node:assert/strict';
import { generateKeyPairSync, createHash } from 'node:crypto';
import { EventEmitter } from 'node:events';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PassThrough, Readable } from 'node:stream';
import { brotliDecompressSync } from 'node:zlib';
import { createHttpServer } from '../../src/index.mjs';
import { authorizationTypedData, buildAuthorization, hashJson } from '../../src/index.mjs';
import { privateKeyToAccount } from 'viem/accounts';

const sender = `0x${'a'.repeat(40)}`;
const recipient = `0x${'b'.repeat(40)}`;
const intent = { intentId: 'intent-api-1', chainId: 8453, action: 'TRANSFER', asset: 'eip155:8453/native', amount: '1000000', sender, recipient, validUntil: 2_000_000_000, nonce: '0' };

type TestServer = ReturnType<typeof createHttpServer>;
type RequestOptions = {
  method?: string;
  headers?: Record<string, string>;
  body?: string;
  stream?: Readable;
};
type MockResponse = EventEmitter & {
  writableEnded: boolean;
  destroyed: boolean;
  status?: number;
  headers?: Record<string, string>;
  body?: string | Buffer;
  writeHead(status: number, headers: Record<string, string>): MockResponse;
  end(value?: string | Buffer): void;
};

async function serverFor(testContext: TestContext) {
  const server = createHttpServer({ observer: async () => ({ chainId: 8453, txHash: `0x${'1'.repeat(64)}`, status: 'PENDING', sender, recipient, finalityState: 'PENDING' }) as any });
  testContext.after(() => server.close()); return server;
}
async function request(server: TestServer, path: string, { method = 'GET', headers = {}, body, stream }: RequestOptions = {}) {
  const req = stream ?? Readable.from(body ? [Buffer.from(body)] : []); Object.assign(req, { method, url: path, headers, socket: { remoteAddress: '127.0.0.1' } });
  const res = new EventEmitter() as MockResponse; res.writableEnded = false; res.destroyed = false; res.writeHead = (status, responseHeaders) => { res.status = status; res.headers = responseHeaders; return res; }; res.end = (value) => { res.writableEnded = true; res.body = value; res.emit('finish'); res.emit('close'); };
  const done = new Promise<void>((resolve) => res.once('finish', resolve)); server.emit('request', req, res); await done; return { status: res.status, headers: res.headers ?? {}, buffer: () => Buffer.from(res.body ?? ''), json: (): any => JSON.parse(Buffer.from(res.body ?? '').toString('utf8')), text: () => Buffer.from(res.body ?? '').toString('utf8') };
}
test('request deadline terminates stalled bodies and rejects slow route work', async (t) => {
  const store = { async health() { await new Promise(resolve => setTimeout(resolve, 80)); return 'ok'; } };
  const server = createHttpServer({ store: store as any, requestTimeoutMs: 20 });
  t.after(() => server.close());
  assert.equal(server.requestTimeout, 20);

  const stalled = new PassThrough();
  const bodyTimeout = await request(server, '/v1/intents', { method: 'POST', headers: { 'content-type': 'application/json' }, stream: stalled });
  assert.equal(bodyTimeout.status, 504);
  assert.equal(bodyTimeout.json().error.code, 'REQUEST_TIMEOUT');
  assert.equal(stalled.destroyed, true);

  const routeTimeout = await request(server, '/health/ready');
  assert.equal(routeTimeout.status, 504);
  assert.equal(routeTimeout.json().error.code, 'REQUEST_TIMEOUT');
});
test('private archive enforces credentials, reviewer scope, tenant isolation and no-store HTTP responses', async (t) => {
  const writer = 'w'.repeat(48), reviewer = 'r'.repeat(48), other = 'o'.repeat(48);
  const credential = (token: string, role: 'writer' | 'reviewer', projectId = 'alpha') => ({ tokenHash: createHash('sha256').update(token).digest('hex'), projectId, environment: 'test' as const, role });
  const server = createHttpServer({ archiveCredentials: [credential(writer, 'writer'), credential(reviewer, 'reviewer'), credential(other, 'writer', 'beta')] });
  t.after(() => server.close());
  const headers = (token: string) => ({ 'content-type': 'application/json', authorization: `Bearer ${token}` });
  const artifact = (n: number) => ({ schema: 'priorseal.verification-bundle.v1', receipt: { receiptId: `private-${n}`, execution: { txHash: `0x${String(n).repeat(64)}`, status: 'CONFIRMED' } } });
  const upload = (token: string, n: number, extra: Record<string, unknown> = {}) => request(server, '/v1/archive', { method: 'POST', headers: headers(token), body: JSON.stringify({ artifact: artifact(n), ...extra }) });
  const anonymous = await request(server, '/v1/archive');
  assert.equal(anonymous.status, 401);
  assert.equal(anonymous.headers['cache-control'], 'private, no-store');
  assert.match(anonymous.headers.vary, /Authorization/);
  assert.equal((await upload(reviewer, 1)).status, 403);
  const saved = await upload(writer, 1);
  assert.equal(saved.status, 201);
  assert.equal(saved.json().verification, 'NOT_VERIFIED_BY_ARCHIVE');
  const entryId = saved.json().id;
  assert.equal((await request(server, `/v1/archive/${entryId}`, { headers: headers(reviewer) })).status, 200);
  assert.equal((await request(server, `/v1/archive/${entryId}`, { headers: headers(other) })).status, 404);
  assert.equal((await upload(other, 2, { supersedesId: entryId })).status, 404);
  assert.equal((await request(server, '/v1/receipts/private-1')).status, 404);
  assert.equal((await upload(writer, 2, { projectId: 'beta' })).status, 400);
  await upload(writer, 2);
  const page = (await request(server, '/v1/archive?limit=1', { headers: headers(reviewer) })).json();
  assert.equal(page.items[0].artifact, undefined);
  assert.equal(page.role, 'reviewer');
  assert.equal(page.retention, 'process_lifetime');
  assert.ok(page.nextCursor);
  const exported = await request(server, '/v1/archive/export?limit=1', { headers: headers(reviewer) });
  assert.equal(exported.status, 200);
  assert.equal(exported.headers['cache-control'], 'private, no-store');
  assert.deepEqual(exported.json().items[0].artifact, artifact(2));
  const continuation = await request(server, `/v1/archive/export?limit=1&cursor=${exported.json().nextCursor}`, { headers: headers(reviewer) });
  assert.deepEqual(continuation.json().items[0].artifact, artifact(1));
  assert.equal(continuation.json().nextCursor, null);
  assert.equal((await request(server, '/v1/archive/export', { headers: headers(other) })).json().items.length, 0);
  assert.equal((await request(server, '/v1/archive/export?limit=26', { headers: headers(writer) })).status, 400);
  assert.equal((await request(server, `/v1/archive?limit=1&cursor=${page.nextCursor}`, { headers: headers(other) })).status, 400);
  assert.equal((await request(server, '/v1/archive?projectId=beta', { headers: headers(writer) })).status, 400);
  const caps = await request(server, '/v1/capabilities');
  assert.equal(caps.status, 200);
  assert.equal(caps.headers['cache-control'], 'no-store');
  assert.equal(JSON.stringify(caps.json()).includes(writer), false);
});
test('API matches pathnames with query strings and uses idempotency safely', async (t) => {
  const server = await serverFor(t); const options = { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'intent-1' }, body: JSON.stringify(intent) };
  const first = await request(server, '/v1/intents?source=test', options); assert.equal(first.status, 201); assert.equal(first.headers['x-content-type-options'], 'nosniff');
  const replay = await request(server, '/v1/intents', options); assert.equal(replay.status, 200); assert.equal(replay.headers['idempotency-replayed'], 'true');
  const conflict = await request(server, '/v1/intents', { ...options, body: JSON.stringify({ ...intent, amount: '2' }) }); assert.equal(conflict.status, 409); assert.equal(conflict.json().error.code, 'IDEMPOTENCY_CONFLICT');
});
test('API rejects unknown fields and unsafe JSON keys without exposing internals', async (t) => {
  const server = await serverFor(t); const unknown = await request(server, '/v1/intents', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...intent, unexpected: true }) }); assert.equal(unknown.status, 400); assert.equal(unknown.json().error.code, 'UNKNOWN_FIELD');
  const badType = await request(server, '/v1/intents', { method: 'POST', body: JSON.stringify(intent) }); assert.equal(badType.status, 415);
  const health = await request(server, '/health/live'); assert.equal(health.json().status, 'ok');
});
test('authorization preparation rejects unsupported intent and exact-call policy combinations before wallet signing', async (t) => {
  const account = `0x${'c'.repeat(40)}`;
  const base = {
    intent,
    principal: { type: 'user', id: 'user-test', account },
    authorizer: { type: 'eip712', address: account },
    delegate: { agentId: 'agent-test', executor: sender },
    issuedAt: 1_000,
    expiresAt: intent.validUntil,
    authorizationNonce: `0x${'4'.repeat(64)}`,
    maxUses: '1',
    audience: 'priorseal',
  };
  const server = createHttpServer({ policy: { allowedChainIds: [8453], maxAmount: '1000000' } });
  t.after(() => server.close());
  const headers = { 'content-type': 'application/json' };
  const legacyMultiChain = await request(server, '/v1/authorizations/prepare', { method: 'POST', headers, body: JSON.stringify({ ...base, intent: { ...intent, chainIds: [1, 8453] } }) });
  assert.equal(legacyMultiChain.status, 400);
  assert.equal(legacyMultiChain.json().error.code, 'INVALID_INTENT');
  const exactIntent = { ...intent, schema: 'priorseal.intent.v2', executionProfile: 'priorseal.execution-profile.exact-call.v1', action: 'CONTRACT_CALL', callTarget: recipient, calldataHash: `0x${'5'.repeat(64)}`, transactionValue: '0' };
  const misleadingPolicy = await request(server, '/v1/authorizations/prepare', { method: 'POST', headers, body: JSON.stringify({ ...base, intent: exactIntent }) });
  assert.equal(misleadingPolicy.status, 403);
  assert.equal(misleadingPolicy.json().error.code, 'POLICY_REJECTED');
  assert.deepEqual(misleadingPolicy.json().error.details.reasonCodes, ['POLICY_EXACT_CALL_SEMANTICS_UNSUPPORTED']);
});
test('authorization preparation rejects policy violations and contradictory execution identities before signing', async (t) => {
  const account = `0x${'c'.repeat(40)}`;
  const base = { intent, principal: { type: 'user', id: 'unapproved-user', account }, authorizer: { type: 'eip712', address: account }, delegate: { agentId: 'agent-test', executor: sender }, issuedAt: 1_000, expiresAt: intent.validUntil, authorizationNonce: `0x${'6'.repeat(64)}`, maxUses: '1' };
  const server = createHttpServer({ policy: { principals: [{ id: 'approved-user', type: 'user', account, authorizerType: 'eip712' }], allowedChainIds: [8453] } });
  t.after(() => server.close());
  const headers = { 'content-type': 'application/json' };
  const disallowed = await request(server, '/v1/authorizations/prepare', { method: 'POST', headers, body: JSON.stringify(base) });
  assert.equal(disallowed.status, 403);
  assert.deepEqual(disallowed.json().error.details.reasonCodes, ['POLICY_PRINCIPAL_NOT_ALLOWED']);
  const approved = { ...base, principal: { ...base.principal, id: 'approved-user' } };
  const contradictory = await request(server, '/v1/authorizations/prepare', { method: 'POST', headers, body: JSON.stringify({ ...approved, delegate: { ...approved.delegate, executor: recipient } }) });
  assert.equal(contradictory.status, 400);
  assert.equal(contradictory.json().error.code, 'INVALID_AUTHORIZATION');
  const { nonce, ...intentWithoutNonce } = intent;
  const missingNonce = await request(server, '/v1/authorizations/prepare', { method: 'POST', headers, body: JSON.stringify({ ...approved, intent: intentWithoutNonce }) });
  assert.equal(missingNonce.status, 400);
  assert.equal(missingNonce.json().error.code, 'INVALID_INTENT');
});
test('observation writes honor Idempotency-Key and return a signed linked receipt', async (t) => {
  const keys = generateKeyPairSync('ed25519');
  const privateKeyPem = keys.privateKey.export({ type: 'pkcs8', format: 'pem' });
  const publicKeyPem = keys.publicKey.export({ type: 'spki', format: 'pem' });
  let calls = 0;
  const txHash = `0x${'1'.repeat(64)}`;
  const server = createHttpServer({ privateKeyPem, publicKeyPem, observer: async () => { calls += 1; return { chainId: 8453, txHash, status: 'CONFIRMED', action: 'TRANSFER', executedAt: 1_000, observedAt: 1_001, sender, recipient, asset: intent.asset, amount: intent.amount, nonce: intent.nonce, confirmations: 12, gasUsed: '21000', transfers: [], blockHash: `0x${'c'.repeat(64)}`, finalityState: 'CONFIRMED', observationSource: 'evm-json-rpc:eip155:8453:configured-1' } as any; } });
  t.after(() => server.close());
  await request(server, '/v1/intents', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(intent) });
  const options = { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'observe-1' }, body: JSON.stringify({ intentId: intent.intentId, chainId: 8453, txHash, confirmations: 12 }) };
  const first = await request(server, '/v1/executions/observe', options);
  const replay = await request(server, '/v1/executions/observe', options);
  assert.equal(first.status, 200);
  const issued = first.json().receipt;
  assert.equal(issued.binding.bound, true);
  assert.equal(replay.headers['idempotency-replayed'], 'true');
  assert.equal(calls, 1);
  const fetched = await request(server, `/v1/receipts/${issued.receiptId}`);
  assert.deepEqual(fetched.json(), issued);
  assert.ok(fetched.headers['x-request-id']);
  const verified = await request(server, '/v1/receipts/verify', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ receipt: fetched.json() }) });
  const bundled = await request(server, `/v1/receipts/${issued.receiptId}/bundle`);
  assert.equal(bundled.status, 200);
  const bundle = bundled.json();
  assert.equal(bundle.schema, 'priorseal.verification-bundle.v1');
  assert.deepEqual(bundle.receipt, issued);
  assert.equal(bundle.keyRegistry.keys[0].keyId, 'default');
  assert.equal(bundle.trust.model, 'PIN_ISSUER_KEY_OUT_OF_BAND');
  const { bundleHash, ...unsignedBundle } = bundle;
  assert.equal(bundleHash, hashJson(unsignedBundle));
  assert.equal(verified.json().result.valid, true);
});
test('pending observations return a durable job handle', async (t) => {
  const txHash = `0x${'7'.repeat(64)}`;
  const queued = { jobId: 'job-pending-1', state: 'QUEUED', attempts: 0, input: { intentId: intent.intentId, chainId: 8453, txHash }, observation: null, result: null, error: null };
  const jobKeys: string[] = [];
  const observationWorker = { async enqueuePersistent(input: any) { jobKeys.push(input.idempotencyKey); return { ...queued, jobId: `job-pending-${jobKeys.length}` }; }, async get() { return queued; } };
  const server = createHttpServer({ observationWorker: observationWorker as any, observer: async () => ({ chainId: 8453, txHash, status: 'PENDING', action: 'TRANSFER', sender, recipient, asset: intent.asset, amount: intent.amount, nonce: intent.nonce, confirmations: 0, transfers: [], finalityState: 'PENDING' }) as any });
  t.after(() => server.close());
  await request(server, '/v1/intents', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(intent) });
  const observationBody = JSON.stringify({ intentId: intent.intentId, chainId: 8453, txHash, confirmations: 12 });
  const observed = await request(server, '/v1/executions/observe', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'observe-cycle-1' }, body: observationBody });
  const replay = await request(server, '/v1/executions/observe', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'observe-cycle-1' }, body: observationBody });
  const restarted = await request(server, '/v1/executions/observe', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'observe-cycle-2' }, body: observationBody });
  assert.equal(observed.status, 200);
  assert.equal(observed.json().observationJob.jobId, 'job-pending-1');
  assert.equal(observed.json().observation.status, 'PENDING');
  assert.equal(replay.json().observationJob.jobId, 'job-pending-2');
  assert.equal(restarted.json().observationJob.jobId, 'job-pending-3');
  assert.equal(jobKeys[0], jobKeys[1]);
  assert.notEqual(jobKeys[1], jobKeys[2]);
});
test('signed authorization is accepted before execution and produces a v3 compliance receipt', async (t) => {
  const keys = generateKeyPairSync('ed25519');
  const privateKeyPem = keys.privateKey.export({ type: 'pkcs8', format: 'pem' });
  const publicKeyPem = keys.publicKey.export({ type: 'spki', format: 'pem' });
  const account = privateKeyToAccount(`0x${'1'.repeat(64)}`);
  const executionIntent = { ...intent, intentId: 'intent-authorized-api', sender: account.address.toLowerCase(), validUntil: 2_000 };
  const draft = buildAuthorization({ intent: executionIntent, principal: { type: 'organization', id: 'org-test', account: account.address }, authorizer: { type: 'eip712', address: account.address }, delegate: { agentId: 'agent-test', executor: account.address }, issuedAt: 1_000, expiresAt: 2_000, authorizationNonce: `0x${'2'.repeat(64)}`, maxUses: '1', audience: 'priorseal', policyHash: `0x${'0'.repeat(64)}` });
  const authorization = buildAuthorization({ ...draft, signature: await account.signTypedData(authorizationTypedData(draft)) });
  const txHash = `0x${'5'.repeat(64)}`;
  let clock = 1_001_000;
  const server = createHttpServer({ privateKeyPem, publicKeyPem, now: () => clock, observer: async () => ({ chainId: 8453, txHash, status: 'CONFIRMED', action: 'TRANSFER', executedAt: 1_100, observedAt: 1_101, sender: account.address.toLowerCase(), recipient, asset: intent.asset, amount: intent.amount, nonce: intent.nonce, confirmations: 12, gasUsed: '21000', transfers: [], blockHash: `0x${'c'.repeat(64)}`, finalityState: 'CONFIRMED', observationSource: 'test' }) as any });
  t.after(() => server.close());
  const accepted = await request(server, '/v1/authorizations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(authorization) });
  assert.equal(accepted.status, 201);
  clock = 1_101_000;
  const authorizationId = accepted.json().authorization.authorizationId;
  const observed = await request(server, '/v1/executions/observe', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ authorizationId, chainId: 8453, txHash, confirmations: 12 }) });
  assert.equal(observed.status, 200);
  assert.equal(observed.json().receipt.schema, 'priorseal.execution-receipt.v3');
  assert.equal(observed.json().receipt.executionStatus, 'CONFIRMED');
  assert.equal(observed.json().receipt.compliance.status, 'COMPLIANT');
  assert.equal(observed.json().receipt.binding.bound, true);
  assert.equal(observed.json().verification.valid, true);
  const verified = await request(server, '/v1/receipts/verify', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ receipt: observed.json().receipt }) });
  assert.equal(verified.json().result.valid, true);
});
test('serves the production console and preserves API 404 responses', async (t) => {
  const staticDir = await mkdtemp(join(tmpdir(), 'priorseal-static-'));
  await writeFile(join(staticDir, 'index.html'), '<!doctype html><title>PriorSeal console</title>');
  await writeFile(join(staticDir, 'app.js'), `globalThis.example = '${'evidence-'.repeat(600)}';`);
  await writeFile(join(staticDir, 'photo.jpg'), Buffer.from([0xff, 0xd8, 0xff, 0xd9]));
  let rateLimitChecks = 0;
  const server = createHttpServer({ staticDir, rateLimiter: { allow() { rateLimitChecks += 1; return true; } } }); t.after(() => server.close());
  const root = await request(server, '/'); const route = await request(server, '/app/receipts'); const missingApi = await request(server, '/v1/missing');
  assert.equal(root.status, 200); assert.match(root.headers['content-type'], /^text\/html/); assert.match(root.text(), /PriorSeal console/);
  assert.equal(route.status, 200); assert.equal(route.text(), root.text());
  const compressed = await request(server, '/app.js', { headers: { 'accept-encoding': 'br, gzip' } });
  assert.equal(compressed.headers['content-encoding'], 'br'); assert.match(brotliDecompressSync(compressed.buffer()).toString(), /globalThis\.example/);
  const image = await request(server, '/photo.jpg'); assert.equal(image.headers['content-type'], 'image/jpeg'); assert.ok(image.headers.etag);
  const notModified = await request(server, '/photo.jpg', { headers: { 'if-none-match': image.headers.etag } }); assert.equal(notModified.status, 304);
  assert.equal(missingApi.status, 404); assert.equal(missingApi.json().error.code, 'NOT_FOUND'); assert.equal(rateLimitChecks, 1);
});

test('HTTP handling awaits a shared limiter and uses the trusted Cloudflare client address', async (t) => {
  let limitedKey: string | undefined;
  const server = createHttpServer({ trustProxy: true, rateLimiter: { async allow(key) { limitedKey = key; return false; } } });
  t.after(() => server.close());
  const response = await request(server, '/v1/version', { headers: { 'cf-connecting-ip': '203.0.113.7', 'x-forwarded-for': '198.51.100.9' } });
  assert.equal(response.status, 429);
  assert.equal(response.json().error.code, 'RATE_LIMITED');
  assert.equal(limitedKey, '203.0.113.7');
});
