#!/usr/bin/env node
// TypeScript source; the matching .mjs file is generated by npm run core:build.

import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const root = fileURLToPath(new URL('..', import.meta.url))
const bundle = join(root, 'examples/web3-agent-kit-integration-spike-v1')

await build({
  entryPoints: [join(bundle, 'verify.source.mjs')],
  outfile: join(bundle, 'verify.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  external: ['node:*'],
  banner: { js: "import { createRequire } from 'node:module'; const require = createRequire(import.meta.url);" },
  legalComments: 'inline',
})
const verifierPath = join(bundle, 'verify.mjs')
await writeFile(verifierPath, (await readFile(verifierPath, 'utf8')).replace(/[ \t]+$/gm, ''))

const files: Record<string, string> = {}
for (const relative of [
  'README.md',
  'fixture/baseline.json',
  'fixture/cases.json',
  'fixture/trust-roots.json',
  'verify.mjs',
]) {
  const bytes = await readFile(join(bundle, relative))
  files[relative] = createHash('sha256').update(bytes).digest('hex')
}
await writeFile(join(bundle, 'fixture/manifest.json'), `${JSON.stringify({
  schema: 'wak-insight-priorseal.fixture-manifest.v1',
  version: 'v1',
  files,
}, null, 2)}\n`)
process.stdout.write(`${JSON.stringify({ status: 'BUILT', files: Object.keys(files).length })}\n`)
