import { useEffect, useState } from 'react'
import { AppShell, CodeValue, Empty, LoadingState, Notice, PageHeader, Status } from '../components'
import { api } from '../lib/api'
import { dateTime } from '../lib/format'
import { RotationDiagnostics } from './RotationDiagnostics'
import type { ApiError, KeyRegistry } from '../types'

const errorMessage = (error: unknown) => { const e = error as ApiError; return (e.code ? e.code + ': ' : '') + (e.message ?? 'Something went wrong.') }

export function KeysPage() { const [registry, setRegistry] = useState<KeyRegistry | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0); useEffect(() => { setLoading(true); setError(''); api.keys().then(setRegistry).catch((caught) => setError(errorMessage(caught))).finally(() => setLoading(false)) }, [reload]); return <AppShell><PageHeader eyebrow="TRUST" title="Key registry">Keys are read directly from the configured PriorSeal API. No private key material is exposed here.</PageHeader>{loading ? <LoadingState label="Loading public key registry..." /> : error ? <section><Notice tone="danger" title="Key registry unavailable">{error}</Notice><button className="button secondary retry-button" onClick={() => setReload((value) => value + 1)}>Try again</button></section> : !registry?.keys.length ? <Empty title="No public keys published">The API returned an empty registry. Verification cannot establish an issuer key until a key is published.</Empty> : <section className="panel key-table"><div className="panel-head"><div><h2>{registry.issuer}</h2><p>{registry.schema} · verifier {registry.verifierVersion ?? '—'}</p></div></div><div className="table-scroll"><table><thead><tr><th>Key</th><th>Algorithm</th><th>Status</th><th>Validity</th><th>Public key</th></tr></thead><tbody>{registry.keys.map((key) => <tr key={key.keyId}><td><strong>{key.keyId}</strong><small>{key.issuer}</small></td><td>{key.algorithm}</td><td><Status value={key.status} small /></td><td>{dateTime(key.validFrom)}<br />{key.validUntil ? 'to ' + dateTime(key.validUntil) : 'No expiry published'}</td><td><CodeValue value={key.publicKey} /></td></tr>)}</tbody></table></div></section>}{registry && <RotationDiagnostics registry={registry} />}</AppShell> }
