import { useState, type ReactNode } from 'react'
import { Link, NavLink, useNavigate } from 'react-router-dom'
import { chains, dateTime, short } from './lib/format'
import type { Receipt } from './types'

export function Logo({ compact = false }: { compact?: boolean }) { return <Link className="logo" to={compact ? '/app' : '/'} aria-label="RunProof home"><span className="logo-mark">R</span><span>RunProof</span></Link> }
export function CopyButton({ value, label = 'Copy' }: { value: string; label?: string }) { const [copied, setCopied] = useState(false); return <button className="copy-button" onClick={async () => { await navigator.clipboard?.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }}>{copied ? 'Copied' : label}</button> }
export function CodeValue({ value, title }: { value?: string | null; title?: string }) { return <span className="code-value" title={title ?? value ?? ''}>{short(value)}{value && <CopyButton value={value} />}</span> }
export function Status({ value, small = false }: { value?: string | null; small?: boolean }) { const text = value ?? 'UNKNOWN'; const tone = /COMPLETED|CONFIRMED|VALID|BOUND|ACTIVE|OK/.test(text) ? 'success' : /FAILED|INVALID|REVERTED|EXPIRED|ERROR|MISMATCH|NOT_FOUND/.test(text) ? 'danger' : /PENDING|INACTIVE|UNDETERMINED|REORGED/.test(text) ? 'warning' : 'neutral'; return <span className={'status ' + tone + (small ? ' small' : '')}><span aria-hidden="true">{tone === 'success' ? '✓' : tone === 'danger' ? '!' : '•'}</span>{text.replaceAll('_', ' ')}</span> }
export function Notice({ tone = 'info', title, children }: { tone?: 'info' | 'warning' | 'danger' | 'success'; title: string; children: ReactNode }) { return <section className={'notice ' + tone}><span className="notice-icon" aria-hidden="true">{tone === 'warning' ? '!' : tone === 'danger' ? '×' : 'i'}</span><div><strong>{title}</strong><p>{children}</p></div></section> }
export function Empty({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <div className="empty"><div className="empty-icon">⌁</div><h3>{title}</h3><p>{children}</p>{action}</div> }
export function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: ReactNode }) { return <label className="field"><span className="field-label">{label}</span>{children}{error ? <span className="field-error">{error}</span> : hint && <span className="field-hint">{hint}</span>}</label> }
export function PageHeader({ eyebrow, title, children, actions }: { eyebrow?: string; title: string; children?: ReactNode; actions?: ReactNode }) { return <div className="page-header"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{children && <p className="lede">{children}</p>}</div>{actions && <div className="header-actions">{actions}</div>}</div> }

const nav = [['Overview', '/app'], ['Quickstart', '/app/quickstart'], ['Create intent', '/app/intents/new'], ['Observe execution', '/app/observe'], ['Audit workspace', '/app/audit'], ['Verify receipt', '/app/verify'], ['Receipts', '/app/receipts'], ['Key registry', '/app/keys'], ['API reference', '/app/api']]
export function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false)
  return <div className="shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="side-top"><Logo compact /><button className="mobile-close" onClick={() => setOpen(false)} aria-label="Close navigation">×</button></div><div className="environment"><span className="live-dot" /> Evidence console <span>Local API</span></div><nav>{nav.map(([label, to]) => <NavLink end={to === '/app'} key={to} to={to} onClick={() => setOpen(false)}>{label}</NavLink>)}</nav><div className="side-bottom"><span>Local session activity</span><small>Only actions from this browser are shown.</small></div></aside><main><header className="app-topbar"><button className="menu" onClick={() => setOpen(true)} aria-label="Open navigation">☰</button><span className="top-title">Execution evidence console</span><div className="topbar-right"><span className="api-state"><span className="live-dot" /> API configurable</span><Link className="text-link" to="/">Marketing site ↗</Link></div></header><div className="page">{children}</div></main></div>
}

export function ReceiptSummary({ receipt }: { receipt: Receipt }) { const navigate = useNavigate(); return <article className="receipt-row"><div><Status value={receipt.outcome} /><strong>{receipt.receiptId}</strong><span>{chains[Number(receipt.execution.chainId)] ?? 'Chain ' + receipt.execution.chainId} · {dateTime(receipt.issuedAt)}</span></div><div className="receipt-row-actions"><CodeValue value={receipt.intentHash} /><button className="text-link" onClick={() => navigate('/app/receipts/' + encodeURIComponent(receipt.receiptId))}>View</button></div></article> }
